<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE jdbc-config [ 
	<!ELEMENT jdbc-config ( config+ ) >
	
	<!ELEMENT config ( url , driver , username , password , auto-commit ) >
		<!ATTLIST config id CDATA #REQUIRED> 
		<!ATTLIST config use (true|false) #REQUIRED> 
	
	<!ELEMENT url (#PCDATA) >
	<!ELEMENT driver (#PCDATA) >
	<!ELEMENT username (#PCDATA) >
	<!ELEMENT password (#PCDATA) >
	<!ELEMENT auto-commit (#PCDATA) >

]>

<jdbc-config>

	<config id="mysql" use="true" >
		<url>jdbc:mysql://localhost:3306/dzfp_project??useUnicode=true&amp;characterEncoding=utf8</url>
		<driver>com.mysql.jdbc.Driver</driver>
		<username>root</username>
		<password>Aa123456</password>
		<auto-commit>true</auto-commit>
	</config>
	
</jdbc-config>